DROP DATABASE IF EXISTS BookMarketplace;
CREATE DATABASE BookMarketplace;
USE BookMarketplace;

CREATE TABLE Locations (
    LocationID INT AUTO_INCREMENT PRIMARY KEY,
    City VARCHAR (100) NOT NULL UNIQUE,
    email VARCHAR (100) NOT NULL UNIQUE,
    pw password VARCHAR (100) NOT NULL UNIQUE
)